@startuml
start
:Enter Expense Data;
: Save as PLANNED;

if () then (Not Invoiced)
else (Invoice Expected)
    fork
        repeat
            : May Update Expense Data;
        repeat while
    fork again
        : Enter { invoiceID };
        : Upload Invoice Copy;
    end fork
    : Save as INVOICED;
endif
:Upload Receipt Copy;
:Save as PAID;

stop
@enduml