@startuml
header Project: Expenses
title Assign Expense Non-Invoiced Flow
(*) --> "
{{
salt
{+
    Recipient: | "<color:#9a9a9a>vendor name   " | <color:Blue>                  Planned
    Amount: | "<color:#9a9a9a>00.00 EUR     "
    Payment: {"<color:#9a9a9a>12.12.2023" }
    Invoice: { (X) Expected | () Non-Invoiced }
    [<color:#9a9a9a>Save      ] | [Close    ]
}
}}
" as initial

initial -[#Red]down-> "
{{
salt
{+
    Recipient: | "<color:Red>Aral Kudamm  " | <color:Blue>                   Planned
    Amount: | "<color:Red>52.43 EUR    "
    Payment: {"<color:Red>20.01.2024" }
    Invoice: { () Expected | (X) <color:Red>Non-Invoiced }
    [<color:Green>Save      ] | [Close    ]
}
}}
" as plannedNoInvoice

plannedNoInvoice -right-> "
{{
salt
{+
    Recipient: | "Aral Kudamm  " | <color:Blue>                   Planned
    Amount: | "52.43 EUR    "
    Payment: {"20.01.2024" }
    Invoice: { () Expected | (X) Non-Invoiced }
    Receipt: | [<color:Green>Upload]
    [Delete     ] | [Close    ]
}
}}
" as plannedNoInvoiceSaved

plannedNoInvoiceSaved -> "
{{
salt
{+
    Recipient: | "Aral Kudamm 161" | <color:Blue>   Due 20.01.2024
    Amount: | "52.43 EUR"
    Payment: {"20.01.2024" }
    Invoice: { () Expected | (X) Non-Invoiced }
    Receipt: | [<color:Green>Upload]
    [Delete     ] | [Close    ]
}
}}
" as due

due -[#Green]down-> "
{{
salt
{+
    Recipient: | Aral Kudamm 161 | <color:Blue>                      Paid
    Amount: | 52.43 EUR
    Payment: |    20.01.2025
    Invoice: { None }
    Receipt: { <&file> | Show }
    [Close     ]
}
}}
" as paid

plannedNoInvoiceSaved -[#Green]-> paid


plannedNoInvoiceSaved -[#Red]down-> "
{{
salt
{+
    Recipient: | "Aral Kudamm  " | <color:Blue>                   Planned
    Amount: | "52.43 EUR    "
    Payment: {"20.01.2024"}
    Invoice: { (X) <color:Red>Expected | () Non-Invoiced }
    [Save      ] | [Delete     ] | [Close    ]
}
}}
" as plannedInvoice
plannedInvoice -down-> "continue in Invoiced Flow" as invoiced

@enduml