@startuml

top to bottom direction
allowmixing
hide empty members

actor User
database DB

package adapters {
    package driven {
        class AccountEndpoint
    }

    package driving {
        class AccountRepositoryAdapter
    }
}


package ports {
    package driven {
        class AccountAppPort
        class AccountDto
        interface AccountDtoMapper
    }

    package driving {
        interface AccountDataMapper
        interface AccountRepoPort
        class AccountData

    }
}
package application {
    class AccountAppService
}
package domain {
    class Account
}

User -d-> AccountEndpoint
AccountRepositoryAdapter -u-> DB


AccountEndpoint --> AccountAppPort
AccountRepositoryAdapter .d.|> AccountRepoPort
AccountAppService .u.|> AccountAppPort
AccountAppService -u-> AccountDtoMapper

AccountAppService -u-> AccountDataMapper
AccountAppService -u-> AccountRepoPort
AccountAppService -d-> Account


@enduml