@startuml
"Assign Expense" as (AExp)
"Upload Receipt Copy" as (ScRsp)
"Download Receipt Copy" as (ShwAcc)
"Finalize Period" as (FinPer)
"Generate Report" as (GenRep)
"Create Account" as (CrAcc)
"Delete Account" as (DelAcc)
(AExp) ..> (ScRsp): <<include>>
Spender --> (AExp)
Spender --> (ShwAcc)
Accounter --> (FinPer)
Accounter --> (ShwAcc)
Accounter --> (CrAcc)
Accounter --> (DelAcc)
(FinPer) ..> (GenRep): <<include>>
(AExp) ..> (CrAcc): <<only after>>
(FinPer) ..> (CrAcc): <<only after>>
(ShwAcc) ..> (AExp): <<only after>>
@enduml
