@startuml
"Add Expense" as (AExp)
"Add Cash Expense" as (ACExp)
"Add Bank Transaction Expense" as (ABTExp)
"Add Credit Card Expense" as (ACCExp)
"Show Account Balance" as (ShwAcc)
"Finalize Period" as (FinPer)
"Create Account" as (CrAcc)
"Delete Account" as (DelAcc)
(ABTExp) --|> (AExp)
(ACExp) --|> (AExp)
(ACCExp) --|> (AExp)
Spender --> (ABTExp)
Spender --> (ACExp)
Spender --> (ACCExp)
Spender --> (ShwAcc)
Accounter --> (FinPer)
Accounter --> (ShwAcc)
Accounter --> (CrAcc)
Accounter --> (DelAcc)
(AExp) ..> (CrAcc)
(FinPer) ..> (CrAcc)
(ShwAcc) ..> (CrAcc)
@enduml
