@startjson
{
    "expenseId": "number",
    "expenseState": ["Planned", "Invoiced", "Due", "PastDue", "Paid"],
    "recipient": "String",
    "purpose": "String",
    "amount": "MoneyString",
    "accruedDate": "DateString",
    "invoiceState": ["Invoiced"],
    "paymentTargetDate": "DateString",
    "paymentType": ["Unknown", "Cash", "CreditCard", "ECCard", "BankTransfer"],
    "invoiceCopy": ["image-file"]
}
@endjson