@startjson
{
    "recipient": "String",
    "purpose": "String",
    "amount": "MoneyString",
    "accruedDate": "DateString",
    "invoiceState": ["Expected", "Invoiced", "NotInvoiced"],
    "paymentTargetDate": "DateString",
    "paymentType": ["Unknown", "Cash", "CreditCard", "ECCard", "BankTransfer"]
}
@endjson