@startuml

top to bottom direction
allowmixing
hide empty members

actor User
database DB

package adapters {
    package driven {
        class AccountEndpoint
    }

    package driving {
        class AccountRepositoryAdapter
    }
}


package ports {
    package driven {
        class AccountApiPort
        class AccountDto
        AccountApiPort -r-> AccountDto

    }

    package driving {
        class AccountData
        interface AccountRepoPort
        AccountRepoPort -l-> AccountData

    }
}
package application {
    class AccountAppService
    interface AccountDataMapper
    interface AccountDtoMapper
}
package domain {
    class Account
}

User -d-> AccountEndpoint
AccountRepositoryAdapter -u-> DB


AccountEndpoint --> AccountApiPort
AccountRepositoryAdapter .d.|> AccountRepoPort
AccountAppService .u.|> AccountApiPort
AccountAppService -r-> AccountDtoMapper

AccountAppService -l-> AccountDataMapper
AccountAppService -u-> AccountRepoPort
AccountAppService -d-> Account
AccountDataMapper -d-> Account
AccountDataMapper -u-> AccountData
AccountDtoMapper -d-> Account
AccountDtoMapper -u-> AccountDto


@enduml