@startwbs
'https://plantuml.com/wbs-diagram

* AccountsList \n/accounts
** AccountDashboard \n/accounts/{accountNo}
*** AssignExpensesForm
*** LoadReceiptDialog
** ReportsDashboard\n/reports
*** ReportPage\nreports/{reportId}
** ErrorPage
@endwbs